name: Java code coverage with Gradle

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'subprojects/**'
      - '**/README.md'
      - '.github/workflows/test_dependencies.yml'

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Calculate and upload coverage report
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: |
          ./gradlew build jacocoTestReport
          bash <(curl -s https://codecov.io/bash )
