name: publish to MavenCentral (over sontype) on release tags (started with "v")

on:
  push:
    tags: [ 'v*' ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create github release
        run: |
          echo "RELEASE_VERSION=" >> $GITHUB_ENV
          ./gradlew getLastChangesFromChangelog -q >> $LAST_RELEASE_NOTE


      - name: Publish with Gradle
        if: ${{ false }}
        env:
          signingKey64: ${{secrets.SIGNING_KEY_64}}
          signingPassword64: ${{secrets.SIGNING_PASSWORD_64}}
          sonatypeUsername: ${{secrets.SONATYPE_USERNAME}}
          sonatypePassword64: ${{secrets.SONATYPE_PASSWORD_64}}
        run: |
          [[ $GITHUB_REF =~ SNAPSHOT ]] && echo "can not publish SNAPSHOT version" && exit 1
          ./gradlew build publishToSonatype closeAndReleaseSonatypeStagingRepository
