name: publish to MavenCentral (over sonatype) on release tags (started with "v")

on:
  push:
    tags: [ 'v*' ]

  workflow_dispatch:

jobs:
  publish:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get release version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF:11}" >> "$GITHUB_ENV"
          echo "RELEASE_TAG=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"

      - name: Get release notes
        run: |
          ./gradlew getLastChangesFromChangelog -q
          echo "RELEASE_NOTE<<EOF_EOF" >> "$GITHUB_ENV"
          ./gradlew getLastChangesFromChangelog -q >> "$GITHUB_ENV"
          echo "EOF_EOF" >> "$GITHUB_ENV"

      - name: Show release information
        run: |
          echo "version=$RELEASE_VERSION"
          echo "tag=$RELEASE_TAG"
          echo "release notes: $RELEASE_NOTE"

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: ${{ env.RELEASE_NOTE }}

      - name: Publish to MavenCentral (over sonatype)
        env:
          signingKey64: ${{secrets.SIGNING_KEY_64}}
          signingPassword64: ${{secrets.SIGNING_PASSWORD_64}}
          sonatypeUsername: ${{secrets.SONATYPE_USERNAME}}
          sonatypePassword64: ${{secrets.SONATYPE_PASSWORD_64}}
        run: |
          [[ $GITHUB_REF =~ SNAPSHOT ]] && echo "can not publish SNAPSHOT version" && exit 1
          ./gradlew build publishToSonatype closeAndReleaseSonatypeStagingRepository
