name: test mocking tool registration dependent of libraries in classpath

on:
  push:
    branches:
      - master
    paths:
      - 'subprojects/dependencies-tests/**'
      - '.github/workflows/test_dependencies.yml'

  pull_request:
    branches:
      - master
    paths:
      - 'subprojects/dependencies-tests/**'
      - '.github/workflows/test_dependencies.yml'

  workflow_dispatch:

jobs:

  test-dependencies:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: publish mockobor to maven local
        env:
          signingKey64: ${{secrets.SIGNING_KEY_64}}
          signingPassword64: ${{secrets.SIGNING_PASSWORD_64}}
        run: ./gradlew publishToMavenLocal

      - name: test dependencies if no mocking tools/only mockito/only easymock etc. available
        run: ./gradlew --project-dir=./subprojects/dependencies-tests check --continue
